### PR TITLE
Remove unused functions and parameters from realtimerobotclient

### PR DESCRIPTION
**Pull request by felixvd**
This PR removes functions and parameters that have no effect (the server has no corresponding functions so the call returns without doing anything).

Autotester: https://autotester.test.mujin.co.jp/?scheduleid=2&pipelineid=257387

### CODE REVIEW

**Comment by kanbouchou** [comment]
Looks good to me, changes in this MR correctly reflects the server side implementation.

passing to @rdiankov

**Comment by felixvd** [comment]
I separate the change to `MoveToDropOff` into its own PR ( https://github.com/mujin/mujincontrollerclientpy/pull/111 ) so this is easier to review.

**Comment by felixvd** [comment]
Just removed another small change that was unrelated. This change set contains nothing that @kanbouchou hasn't reviewed yet. 

Please merge at your convenience @rdiankov

**Comment by rdiankov** [comment]
thanks

**Pull request merged**
