### PR TITLE
Update description about fastDetectionMode

### PR DESCRIPTION
**Pull request by wkentaro**
- Depends on the upstream, so please wait for that to be merged.

### CODE REVIEW

**Comment by jerasman** [comment]
@yoshikikanemoto Can you merge? Just docs.
Can you give me permission to merge to this repo?

**Comment by wkentaro** [comment]
I just noticed this, so I guess it will be updated once the upstream change got merged?

image

**Comment by felixvd** [comment]
Yes, see [these instructions](https://github.com/mujin/mujincontrollerclientpy#how-to-re-generate-controllergraphclientpy)

**Comment by cielavenir** [comment]
@wkentaro @felixvd I wrote an interesting article in jhbuilddocs.

**Comment by cielavenir** [comment]
btw running that locally showed your updated description.

**Pull request closed without merging**
