### PR TITLE
Implement AddObjectToObjectSet() to support single snapshot autoregis…

### PR DESCRIPTION
**Pull request by RobertYe**
this is to create addobjecttoobjectset api in controllerclientpy

### CODE REVIEW

**Comment by rdiankov** [comment]
hmm....... in one of the original meetings we had, we all agreed to have a WebAPI call to append in order to avoid race conditions...

**Comment by RobertYe** [comment]
@rdiankov can you explain more on this comment? as far as i can see, we are doing append already.

**Comment by rdiankov** [comment]
append needs to happen on webstack side, not in the client. When it is in the client, race conditions occur.

**Comment by bucketzxm** [comment]
Is someone working on this feature in webstack now ?

**Comment by rdiankov** [comment]
this is deprecated merge request.
@ziyan already made the correct commits to webstack and visionmanager and the clients `ModifySceneAddReferenceObjectPK` and `ModifySceneRemoveReferenceObjectPK`. the question is, is detectors using the new APIs?

**Pull request closed without merging**
