### PR TITLE
Remove GetInertiaChildJointStartValues

### PR DESCRIPTION
**Pull request by felixvd**
This function does not exist in `realtimerobottask3.py`, so the call goes nowhere.

### CODE REVIEW

**Comment by yoshikikanemoto** [comment]
@kanbouchou it seems atilla added this function. is there any chance that just we forgot to merge some of his change in server sdie?

**Comment by kanbouchou** [comment]
> @kanbouchou it seems atilla added this function. is there any chance that just we forgot to merge some of his change in server sdie?

I'll check and get back, most likely there was a server code for this but we ended up not using it.

**Comment by felixvd** [comment]
How about we save the time and implement the function when there is a need? Apparently no one has needed it, and the original commit from 5 years ago says `temp hack for inertia child trajectory`.

**Comment by kanbouchou** [comment]
> How about we save the time and implement the function when there is a need? Apparently no one has needed it, and the original commit from 5 years ago says `temp hack for inertia child trajectory`.

We were trying to do moment of inertia identification but could not complete it. I think this api was added as part of the effort. If I remember correctly, it was trying to access the child links of a given robot or something. I think it's safe to remove this.

**Comment by felixvd** [comment]
Let's remove it for now and add it back when we revive that effort.

**Comment by yoshikikanemoto** [comment]
thanks

**Pull request merged**
